// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cncvmnaocaossysozvln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuY3ZtbmFvY2Fvc3N5c296dmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjAyMzEsImV4cCI6MjA2NDE5NjIzMX0.7TzPl_4cEPzb1SxUHiwiOZdyzl4ChQcKu44uPSG-258";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);